### ISSUE TITLE
Error when forking multiple changesets that include foreign key constraints

### ISSUE THREAD

**Issue by NGRichter** [quantumdb/quantumdb#89]
<details>
  <summary>Error</summary>
  
java.lang.IllegalStateException: Identities of parent table: table_e431767ad3 should be migrated before copying records of: table_a95538de33

	at com.google.common.base.Preconditions.checkState(Preconditions.java:510)
	at io.quantumdb.core.backends.planner.PlanValidator.verifyThatNotNullableForeignKeysAreSatisfiedBeforeInitialCopy(PlanValidator.java:189)
	at io.quantumdb.core.backends.planner.PlanValidator.validate(PlanValidator.java:25)
	at io.quantumdb.core.planner.PostgresqlMigrator.applySchemaChanges(PostgresqlMigrator.java:64)
	at io.quantumdb.core.migration.Migrator.migrate(Migrator.java:97)

</details>

I was trying to build a unit test that will test forking multiple changesets, including forking tables with foreignkey constraints. I am getting this error and I do not know how to fix it.

<details>
  <summary>The code</summary>
  
	@BeforeClass
	public static void performEvolution() throws SQLException, MigrationException {
		setup.insertTestData();

		origin = setup.getChangelog().getLastAdded();

		setup.getChangelog().addChangeSet("test1", "Nick Richter",
				SchemaOperations.addColumn("payments", "store_id", integer()),
				SchemaOperations.addForeignKey("payments", "store_id").referencing("stores", "id"));

		setup.getChangelog().addChangeSet("test2", "Nick Richter",
				SchemaOperations.createTable("country")
						.with("id",bigserial(), PRIMARY_KEY)
						.with("country", varchar(), NOT_NULL)
						.with("ceo", integer()),
				SchemaOperations.addForeignKey("country","ceo").referencing("staff", "id"));

		setup.getChangelog().addChangeSet("test3", "Nick Richter",
				SchemaOperations.addColumn("paychecks", "tax", numeric(2,2), "'0.21'", NOT_NULL),
				SchemaOperations.addColumn("stores", "country", bigint()),
				SchemaOperations.addForeignKey("stores", "country").referencing("country", "id"));

		target = setup.getChangelog().getLastAdded();
		setup.getBackend().persistState(setup.getState());

		setup.getMigrator().migrate(origin.getId(), target.getId());

		state = setup.getBackend().loadState();
	}

</details>

The code is based on AddForeignKeyToPaymentsTable where I typed some additional changesets. The plan was to also drop some changesets to see if the correct tables were dropped.

**Comment by michaeldejong** [comment]
Ok, this one seems a little tricky. I need some time to dive a little deeper into this one.
